server:
  port: 8080

logging:
  level:
    com:
      lanclass: DEBUG


spring:
  datasource:
      url: jdbc:mysql://gz-cynosdbmysql-grp-iezap38d.sql.tencentcdb.com:24105/classroom?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: Lsh5258!
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  type-aliases-package: com.lanclass.entity
  mapper-locations: classpath:Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


#spring: mvc: pathmatch: matching-strategy: ANT_PATH_MATCHER
#
#spring:
#  mvc:
#    pathmatch:

